---
# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"

# Shrink default JVM heap.
replicas: 1
# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "1Gi"
  limits:
    cpu: "2000m"
    memory: "1Gi"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 10Gi
