---
debug: true
contextTimeout: 5

server:
  port: "8081"
  host: "0.0.0.0"
  env: "local"
  useRedis: false

services:
  # paymentServiceURL: "http://payment-service/api/payment"
  # paymentServiceURL: "http://localhost:8081/api/payment"

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  name: "payment-service"
