---
debug: true
contextTimeout: 5

server:
  port: "8082"
  host: "127.0.0.1"
  env: "local"
  useRedis: false

services:
  categoryServiceURL: "http://localhost:8081/api/category/"
  variantServiceURL: "http://localhost:8082/api/variant/"

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  username: "titus"
  password: "saota1278"
  name: "item-service"
