apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-deployment
  labels:
    app: item-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: item-service
  template:
    metadata:
      labels:
        app: item-service
    spec:
      containers:
        - name: item-service
          image: item-service
          env:
            - name: ENV
              value: dev
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "250m"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: item-service
#   labels:
#     app: item-service
# spec:
#   selector:
#     app: item-service
#   type: LoadBalancer
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#       nodePort: 30001
