---
debug: true
contextTimeout: 5

server:
  port: "8082"
  host: "192.168.0.11"
  env: "local"
  useRedis: false

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  username: "titus"
  password: "saota1278"
  name: "variant-service"

nsq:
  host: "nsqd"
  port: 4150
...