logstashPipeline:
  logstash.conf: |
    input {
      jdbc {
      	jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/postgresql.jar"
        jdbc_connection_string => "jdbc:postgresql://postgres-replica-postgresql-ha-pgpool:5432/item-service"
        jdbc_user => "postgres"
        jdbc_password => "postgres"
        jdbc_driver_class => "org.postgresql.Driver"
        statement => "SELECT * FROM items LIMIT :size OFFSET :offset + 700000"
        use_column_value => true
    	tracking_column => updated_at
    	jdbc_paging_enabled => true
    	jdbc_paging_mode => "explicit"
    	jdbc_page_size => 1000
      	clean_run => false
    	schedule => "* * * * *"
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-master:9200"]
        index => "items"
        document_id => "items_%{id}"
        doc_as_upsert => true
      }
    }

image: "logstash-local"
imageTag: "latest" 
imagePullPolicy: "Never"
resources:
  requests:
    cpu: "100m"
    memory: "1536Mi"
  limits:
    cpu: "1000m"
    memory: "1536Mi"

